#!/bin/bash

docker build --build-arg MAGENTO_VERSION=2.3.3 -f $DOCKERFILE_PATH -t $DOCKER_REPO:2.3.3 .
docker build --build-arg MAGENTO_VERSION=2.3.2-p2 -f $DOCKERFILE_PATH -t $DOCKER_REPO:2.3.2-p2 .
docker build --build-arg MAGENTO_VERSION=2.3.2 -f $DOCKERFILE_PATH -t $DOCKER_REPO:2.3.2 .